// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKArP_3X_g5qFuQP-T1efx774x2LobOdM',
    appId: '1:979215006620:web:9362ad1cad55c578ad6659',
    messagingSenderId: '979215006620',
    projectId: 'task-manager-47bef',
    authDomain: 'task-manager-47bef.firebaseapp.com',
    storageBucket: 'task-manager-47bef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQeEgeRqAra2jhVv0-dPRY1VBHDRKXljY',
    appId: '1:979215006620:android:79e1b4b462aaa443ad6659',
    messagingSenderId: '979215006620',
    projectId: 'task-manager-47bef',
    storageBucket: 'task-manager-47bef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7JTpBDC8KRHTTPm3t-n5WeAy2qL4NWnk',
    appId: '1:979215006620:ios:89d457f7d091d3d4ad6659',
    messagingSenderId: '979215006620',
    projectId: 'task-manager-47bef',
    storageBucket: 'task-manager-47bef.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7JTpBDC8KRHTTPm3t-n5WeAy2qL4NWnk',
    appId: '1:979215006620:ios:89d457f7d091d3d4ad6659',
    messagingSenderId: '979215006620',
    projectId: 'task-manager-47bef',
    storageBucket: 'task-manager-47bef.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKArP_3X_g5qFuQP-T1efx774x2LobOdM',
    appId: '1:979215006620:web:2b0311f74a7d7d9aad6659',
    messagingSenderId: '979215006620',
    projectId: 'task-manager-47bef',
    authDomain: 'task-manager-47bef.firebaseapp.com',
    storageBucket: 'task-manager-47bef.firebasestorage.app',
  );

}